language: android
jdk: oraclejdk7

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8
    - ANDROID_API_LEVEL=23
    - ANDROID_BUILD_TOOLS_VERSION=23.0.2

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL

env:
    matrix:
      - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a ANDROID_ABI_IMAGE=sys-img-armeabi-v7a-android-23 #Marshmallow 6.0
      - ANDROID_TARGET=android-22  ANDROID_ABI=armeabi-v7a ANDROID_ABI_IMAGE=sys-img-armeabi-v7a-android-21 #Lollipop 5.1
      - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a ANDROID_ABI_IMAGE=sys-img-armeabi-v7a-android-19 #KitKat 4.4
      - ANDROID_TARGET=android-16  ANDROID_ABI=armeabi-v7a ANDROID_ABI_IMAGE=sys-img-armeabi-v7a-android-16 #JellyBean 4.1.x

# Emulator Management: Create, Start and Wait
before_script:
  - echo y | android update sdk --no-ui --all --filter $ANDROID_ABI_IMAGE
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew connectedCheck -PdisablePreDex --info
