language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-23 #Marshmallow 6.0
    - sys-img-armeabi-v7a-android-22 #Lollipop 5.1
    - sys-img-armeabi-v7a-android-19 #KitKat 4.4
    - sys-img-armeabi-v7a-android-16 #JellyBean 4.1.x

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8
env:
    matrix:
      - ANDROID_SDKS=android-23    ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a
      - ANDROID_SDKS=android-23    ANDROID_TARGET=android-22  ANDROID_ABI=armeabi-v7a
      - ANDROID_SDKS=android-23    ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
      - ANDROID_SDKS=android-23    ANDROID_TARGET=android-16  ANDROID_ABI=armeabi-v7a

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - android list target
  - ./gradlew connectedAndroidTest
